### ISSUE TITLE
codec can;t decode byte error with Unity Catalog

### ISSUE THREAD

**Issue by bradlindblad** [alexmalins/harlequin-databricks#7]
#### What is the issue?

When loading the data catalog - unity catalog, I receive this error:

```
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 2481: character maps to <undefined>
```

#### Steps to reproduce

1. Load a unity catalog connection

#### Environment

This error DOES NOT occur on WSL, but in powershell and cmd prompt.

OS version: Windows 10
Python version: 3.12
harlequin-databricks version: 0.3.0
harlequin version: 1.21.0
Installed via: pip

**Comment by alexmalins** [comment]
Hey @bradlindblad 
Firstly I'm sorry for the slow response - for some reason I missed notifications of these issues so only found out about them now.

Can you please provide a full trace back of the error? 

Also are you loading harlequin-databricks using the `--skip-legacy-indexing` CLI flag?

Potentially this could be an issue with this adapter, a Harlequin issue, or even an issue with the Databricks Python SQL connector. Posting the full trace back will help diagnose.

**Comment by alexmalins** [comment]
The problem is [probably because](https://stackoverflow.com/questions/68481023/unable-to-reproduce-unicodedecodeerror-in-windows-with-sample-data) Windows is attempting to decode a unicode string using CP-1252 when it is actually encoded with UTF-8.

The trace back will tell us where that is occurring, and therefore where we need to tell the decoding to use UTF-8 rather than resorting to the OS's default.

**Comment by alexmalins** [comment]
Hey @bradlindblad I think I found and fixed the issue - please can you try again with v0.3.1? Run `pip install --upgrade harlequin-databricks` to get the latest version

**Comment by bradlindblad** [comment]
Everything works well now! Thanks!
